### ISSUE TITLE
Add links for Changing Spaces Campaign

### ISSUE THREAD

**Issue by brebory** [InspiredAccessFoundation/uct-locator#87]
In order to make the affiliation with the Changing Spaces Campaign more clear, we should discuss adding links to the campaign's website. These links could be in the application itself, maybe on the homepage, or an About page.

Additionally, we could include a section in the README.md to talk about the Changing Spaces Campaign and add a link there.

http://www.changingspacescampaign.org/

[This StackOverflow answer](https://stackoverflow.com/a/62028885) may help with creating an external link.

**Comment by josephmaxwellhyland** [comment]
[This StackOverflow answer](https://stackoverflow.com/a/62028885) may be helpful
